### PR TITLE
[ Enhance ]  Make CLI simpler & stronger by Commander.js

### LINKED ISSUE #88: [ Bug ]  Wrong behavior with unknown parameters
I install `babel-upgrade` globally, and then run `babel-upgrade --help`, it outputs as the same of "without parameter": check `package.json` & show the diff result.

I think it should show the **Command-line usage**, or "Unknown --help parameter" at least...

### PR DESCRIPTION
**Pull request by TechQuery**
- [x] [ Add ]  Make CLI simpler & stronger by Commander.js
 - [x] [ Add ]  Git precommit hook for testing

Fix #88

### CODE REVIEW

File: src/bin.js [hunk 1]
```diff
@@ -41,21 +40,17 @@ function parseOptions(args, availableOptions) {
       console.log("We suggest using the new 'overrides' option instead of nested .babelrc's, can check out http://new.babeljs.io/docs/en/next/babelrc.html#overrides");
       console.log("");
     }
-    paths.forEach(p => writeBabelRC(p, upgradeOptions));
+
+    for (let path of paths)  writeBabelRC(path, upgradeOptions);
```
Comment (aulisius) [inline src/bin.js]: Any reason for this change?

File: src/bin.js [hunk 2]
```diff
@@ -41,21 +40,17 @@ function parseOptions(args, availableOptions) {
...
   }
 
-  mochaOpts.forEach(p => writeMochaOpts(p, upgradeOptions));
+  for (let path of mochaOpts)  writeMochaOpts(path, upgradeOptions);
```
Comment (aulisius) [inline src/bin.js]: Again, any reason for this change?

File: src/bin.js [hunk 3]
```diff
@@ -41,21 +40,17 @@ function parseOptions(args, availableOptions) {
...
   // TODO: allow passing a specific path
   await writePackageJSON(upgradeOptions);
 
-  // TODO: add smarter CLI option handling if we support more options
-  if (cliOptions.installDeps) {
-    if (cliOptions.write) {
-      console.log('Installing new dependencies');
-      await installDeps();
-    } else {
-      console.log('Run babel-upgrade with --write (or) -w and --install for it to install the newly added dependencies');
```
Comment (aulisius) [inline src/bin.js]: Is this warning covered by `Commander`? As in, can Commander itself say something like `--install has to be provided with --write`?

File: package.json [hunk 4]
```diff
@@ -45,6 +47,7 @@
     "@babel/core": "^7.0.0",
     "@babel/preset-env": "^7.0.0",
     "babel-core": "^7.0.0-bridge.0",
+    "husky": "^0.14.3",
```
Comment (ljharb) [inline package.json]: please don't use husky; auto-installing git hooks is supremely dangerous and not worth the effort, since CI is the only reliable enforcement.

File: package.json [hunk 5]
```diff
@@ -27,6 +28,7 @@
   "license": "MIT",
   "dependencies": {
     "@babel/polyfill": "^7.0.0",
+    "commander": "^2.18.0",
```
Comment (ljharb) [inline package.json]: why not yargs?

Comment (TechQuery) [reply package.json]: I don't the style of `yargs` API, and I know more about `commander`.

Comment (ljharb) [reply package.json]: we should get the opinions of babel maintainers and their preferences, since that’s who will be maintaining it.

Comment (suchipi) [reply package.json]: We are already using commander for babel-cli, so using commander here too seems fine. https://github.com/babel/babel/blob/master/packages/babel-cli/package.json#L22

File: src/bin.js (hunk 1 above)
Comment (TechQuery) [reply src/bin.js]: It will be more efficient to use keywords & statements than methods & callbacks, because Babel 7 core has dropped the support of old Node.JS.

Comment (ljharb) [reply src/bin.js]: This isn’t actually more efficient - it uses the iterator protocol instead of the quote fast array method.

Older stuff is almost always faster than newer stuff.

Comment (ljharb) [reply src/bin.js]: Not in latest v8 - they made the array methods identically as fast as for loops.

File: readme.md [hunk 6]
```diff
@@ -222,7 +222,7 @@ npx babel-upgrade --write --install
 - Maybe the version should just reflect the version that it targets?
 
 ## Development
-```sh
-$ npm i
-$ npm start
+```Shell
```
Comment (suchipi) [inline readme.md]: why did you change the language here? Does `Shell` work in GitHub?

Comment (aulisius) [reply readme.md]: It does work. but so does sh.

Comment (suchipi) [reply readme.md]: okay, cool

**Comment by TechQuery** [comment]
@suchipi Any problem in about 1.5 month?

**Comment by suchipi** [comment]
Sorry, I forgot about this
